Repository Inria-Asclepios/medInria-public, pull requests merged in 2018-03, with the labels that each got.

#319 [warnings] rm warnings seen in Jenkins compil
  src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx
  src/medVtkInria/vtkImageView/vtkImageView.cxx
  src/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Florent approved

#316 [medToolBox] handleDisplayError by default
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
  src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
  src-plugins/itkFilters/itkFiltersToolBox.cpp
  src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp
  src-plugins/medBinaryOperation/medBinaryOperationToolBox.cpp
  src-plugins/medMaskApplication/medMaskApplicationToolBox.cpp
  src/medCore/gui/toolboxes/medToolBox.cpp
  src/medCore/process/medRunnableProcess.cpp
Labels: Florent approved

#254 [manualRegistration] harmonize registration algo, use undo/redo
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.cpp
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.h
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
  src-plugins/manualRegistration/manualRegistration.cpp
  src-plugins/manualRegistration/manualRegistration.h
  src-plugins/manualRegistration/manualRegistrationToolBox.cpp
  src-plugins/manualRegistration/manualRegistrationToolBox.h
  src/medCore/gui/toolboxes/medRegistrationSelectorToolBox.cpp
  src/medRegistration/itkProcessRegistration.cpp
  src/medRegistration/itkProcessRegistration.h
Labels: Florent approved

#350 [ITK] switch to V4.11
  src/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.cxx
  src/medVtkInria/vtkDataManagement/vtkMetaImageData.cxx
Labels: Florent approved

#352 Added debug message to all SQL queries
  src/medCore/database/medDatabaseController.cpp
  src/medCore/database/medDatabaseController.h
  src/medCore/database/medDatabaseImporter.cpp
  src/medCore/database/medDatabaseReader.cpp
  src/medCore/database/medDatabaseRemover.cpp
Labels: Mathilde approved

#365 [cmake] c++11 flag
  CMakeLists.txt
Labels: Florent approved

#339 [vtkDataManagement] Fix .mesh reading bug
  src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx
  src/medVtkInria/vtkDataManagement/vtkMetaDataSet.h
  src/medVtkInria/vtkDataManagement/vtkMetaSurfaceMesh.cxx
  src/medVtkInria/vtkDataManagement/vtkMetaSurfaceMesh.h
  src/medVtkInria/vtkDataManagement/vtkMetaVolumeMesh.cxx
  src/medVtkInria/vtkDataManagement/vtkMetaVolumeMesh.h
Labels: Mathilde approved

#343 [Diffeo] separate spacing, size errors. Rm origin error
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.cpp
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.h
  src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
  src/medCore/gui/toolboxes/medToolBox.cpp
  src/medCore/process/medAbstractProcess.h
Labels: Florent approved

#346 [Export] guess extension from filename if needed
  src/medCore/database/medDataManager.cpp
Labels: Florent approved

#367 [AbstractLayeredView] Fix add data twice
  src/medCore/views/medAbstractLayeredView.cpp
Labels: Florent approved, Mathilde approved

#333 [medToolBox] standardize on process success
  app/medInria/medFilteringWorkspace.cpp
  app/medInria/medFilteringWorkspace.h
  app/medInria/medSegmentationWorkspace.cpp
  app/medInria/medSegmentationWorkspace.h
  src-plugins/reformat/medReformatWorkspace.cpp
  src-plugins/reformat/medReformatWorkspace.h
  src/medCore/gui/medSelectorWorkspace.cpp
  src/medCore/gui/medSelectorWorkspace.h
  src/medCore/gui/toolboxes/medToolBox.cpp
  src/medCore/gui/toolboxes/medToolBox.h
Labels: Florent approved
